apiVersion: v1
data:
  spring.data.mongodb.uri: mongodb://root:pwwrd@mongo.anthos.svc.cluster.local:27017/test_db?directConnection=true&authSource=admin
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: ""
  labels:
    app: mongo
  name: mongo-config
  namespace: anthos
data:
  mongod.conf: |
    storage:
      dbPath: /var/lib/mongodb
    systemLog:
      destination: file
      logAppend: true
      path: /var/log/mongodb/mongod.log
    net:
      port: 27017
      bindIp: 0.0.0.0
    processManagement:
      timeZoneInfo: /usr/share/zoneinfo
    security:
      authorization: enabled
