apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-delay
  namespace: ps
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - ps
    labelSelectors:
      app: my-app
  delay:
    latency: "200ms"
