apiVersion: apps/v1
kind: Deployment
metadata:
  name: anthos-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anthos-app
  template:
    metadata:
      labels:
        app: anthos-app
    spec:
      containers:
      - name: anthos-app
        image: knoah98/config:1.3.16  # Replace with your image
        imagePullPolicy: Always
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        env:
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://postgres:5432/apigee_x_db
        envFrom:
          - secretRef:
              name: anthos-secrets
          - configMapRef:
              name: dataconfig      
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: anthos-app-service
spec:
  selector:
    app: anthos-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

