apiVersion: apps/v1
kind: Deployment
metadata:
  name: dashboard-deployment
  labels:
    app: dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
        - name: dashboard
          image: knoah98/config:1.2.1 # Replace with your actual image
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_API_URL
              value: "http://anthos-app-service.anthos.svc.cluster.local:8080" # Replace with your backend service
---
apiVersion: v1
kind: Service
metadata:
  name: dashboard-service
spec:
  selector:
    app: dashboard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer       
