apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-partition-transactionhistory
  namespace: bank-of-anthos
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - bank-of-anthos
    labelSelectors:
      "app": "transactionhistory"
  direction: to
  target:
    selector:
      namespaces:
        - bank-of-anthos
      labelSelectors:
        "app": "ledger-db"
    mode: all
  duration: "100s"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-partition-frontend
  namespace: bank-of-anthos
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - bank-of-anthos
    labelSelectors:
      "app": "balancereader"
  direction: to
  target:
    selector:
      namespaces:
        - bank-of-anthos
      labelSelectors:
        "app": "ledger-db"
    mode: all
  duration: "100s"
---
apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-partition-paymentsvc
  namespace: bank-of-anthos
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - bank-of-anthos
    labelSelectors:
      "app": "ledgerwriter"
  direction: to
  target:
    selector:
      namespaces:
        - bank-of-anthos
      labelSelectors:
        "app": "ledger-db"
    mode: all
  duration: "100s"

