apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: network-partition
spec:
  action: partition
  mode: all
  selector:
    namespaces:
      - ps
    labelSelectors:
      "app": "my-app"
  direction: to
  target:
    selector:
      namespaces:
        - ps
      labelSelectors:
        "app": "postgres"
    mode: all
  duration: "100s"

